apiVersion: v1
kind: ConfigMap
metadata:
  name: pi-hole-custom-dnsmasq
  namespace: pi-hole
data:
  02-custom.conf: |
    address=/argo.lan/10.0.0.243
    address=/ha.lan/10.0.0.243
    address=/home-assistant.lan/10.0.0.243
  custom.list: |
    10.0.0.243 argo.lan
    10.0.0.243 ha.lan
    10.0.0.243 home-assistant.lan
