apiVersion: v1
kind: ConfigMap
metadata:
  name: pi-hole-custom-dnsmasq
  namespace: pi-hole
data:
  02-custom.conf: |
    address=/argo.local/10.0.0.243
    address=/ha.local/10.0.0.243
    address=/home-assistant.local/10.0.0.243
