apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: pihole
  annotations:
    metallb.io/loadBalancerIPs: 10.0.0.240
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: web
      port: 8543
      targetPort: 80
      protocol: TCP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: pihole-web
#   namespace: pihole
# spec:
#   type: ClusterIP
#   selector:
#     app: pihole
#   ports:
#     - name: web
#       port: 80
#       targetPort: 80
#       protocol: TCP
