apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-chart-config.yaml
  - gateway-class.yaml
  - gateway.yaml
  - cluster-roles.yaml
  - routes/argo.yaml
  - routes/home-assistant.yaml
