apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-chart-config.yaml
  - gateway-class.yaml
  - gateway.yaml
  - cluster-roles.yaml
  - argo-route.yaml
  - home-assistant-route.yaml
