apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-map.yaml
  - deployment.yaml
  - ingress-class.yaml
  - role-binding.yaml
  - role.yaml
  - service-account.yaml
  - service.yaml