apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
  # annotations:
  #   metallb.io/loadBalancerIPs: 10.0.0.243
spec:
  valuesContent: |-
    metadata:
    service:
      type: LoadBalancer
      loadBalancerIP: 10.0.0.243
